### ISSUE TITLE
If there is more than one cursor on the same line, numbers are not inserted correctly.

### ISSUE THREAD

**Issue by umeruma** [tsuyoshiwada/sequential-number#1]
```
var = test[_] + test[_] + test[_];
var = hoge[_] + hoge[_] +hoge[_];
```

上記の "_" のように、同一の行に複数連番を入力しようとすると、

```
var = test[01] + tes02t[] + t03est[];
var = hoge[04] + hog05e[] +h06oge[];
```

となり、正しい位置に挿入が行われません。

**Comment by wadackel** [comment]
@umeruma さんIssueありがとうございます。

こちらでも同じバグを確認できました。
`sequential-number@0.3.2`で修正してみましたので、パッケージのアップデートをしてみていただけると助かります。

**Comment by umeruma** [comment]
@tsuyoshiwada さん、早々の対応ありがとうございます。
v0.3.2 にて再現しないこと確認できました！

**Comment by wadackel** [comment]
ご確認ありがとうございます！
問題無さそうなのでCloseいたします。
