### ISSUE TITLE
Unable to open from command palette (when pressing enter)

### ISSUE THREAD

**Issue by ecker00** [tsuyoshiwada/sequential-number#3]
When running "Sequential Number: Open" from the Atom "command palette" by pressing ENTER, it instantly closes the Sequential Number window. When clicking the command palette with the mouse or opening it with the "ctrl-alt-0" hotkey it works fine.

It seems that it needs a little delay before activating the ":close" EventListener, to ignore the release of the Enter key, so it won't instantly trigger "sequential-number:close" when opening.

Side note: Very good package! Nice and flexible way of inserting number sequences.

**Comment by wadackel** [comment]
Hi @ecker00. Thank you for issue and PR.

After merging the PR that you sent, it has released.
Check for the version 0.3.3 :+1:

**Comment by ecker00** [comment]
I realise that I didn't test my fix properly. It only solves the issue on first launch, but the bug remains for consecutive use, because the delayed EventListener is only setup on first launch. I've never written any CoffeeScript before, so it was hard for me to work with. Maybe you see a better solution to this issue?

**Comment by wadackel** [comment]
Thank you for checked.
Not only initialization, it was to perform the bind/unbind in accordance with the display switching.
Please give me the check since the release as v0.3.4.

**Comment by ecker00** [comment]
I looked over your new code, that was a lot more complicated than I expected. But very nice fix, it works perfectly now. Thank you!

**Comment by wadackel** [comment]
Thank you, too.
This Issue will close because it has to work in my environment.
