### ISSUE TITLE
Feature Request: BaseX / alphanumeric support

### ISSUE THREAD

**Issue by flyinbutrs** [tsuyoshiwada/sequential-number#5]
It'd be great to be able to specify an optional base for the numbers (mostly for hex, but I'm sure others have use for other bases)...  so maybe:

```
<start> <operator> <step> : <digit> : <base>
```

**Comment by wadackel** [comment]
Hi @flyinbutrs 
Thank you for feature request!

Would it be possible to show specific examples of the expected values?

**Comment by flyinbutrs** [comment]
So for this:

`0 + 1 : 0 : 16`

It'd output this:

```
0
1
2
3
4
5
6
7
8
9
a
b
c
d
e
f
10
```

or `0 + 1 : 0 : 8` would output

```
0
1
2
3
4
5
6
7
10
```

etc. Base 16 is really the one I want most, because hex is used all over the place in computing.

**Comment by wadackel** [comment]
It is a very good idea!
Add option in the v0.4.0. Please wait next release.

**Comment by wadackel** [comment]
The v0.4.0 released. if possible, Please update to new version.
Will it work as expected?

**Comment by flyinbutrs** [comment]
Wonderful, works! Tested base 16, base 8, and binary:

```
0
1
10
11
100
101
110
111
1000
1001
1010
1011
1100
1101
1110
1111
10000
```

**Comment by wadackel** [comment]
What a relief :smile:
Thanks for the great idea. This issue will close, because the no problem.
