### ISSUE TITLE
compatiblity with sublime-style-column-selection

### ISSUE THREAD

**Issue by nheath** [tsuyoshiwada/sequential-number#7]
After installing this package, I couldn't get https://atom.io/packages/Sublime-Style-Column-Selection to work. Holding the modifier key and dragging doesn't create cursors with this installed. After disabling this package, column-selection works again

**Comment by wadackel** [comment]
Thanks for issues.

It was tested in a state in which the [Sublime Style Column Selection](https://atom.io/packages/Sublime-Style-Column-Selection) and installed the only [sequential number](https://atom.io/packages/sequential-number).

It looks to work normally.

![capture](https://cloud.githubusercontent.com/assets/5393238/18941308/0794dfd4-864b-11e6-8e89-fa751c485def.gif)

Is there a likely package will cause the other?

**Comment by wadackel** [comment]
This Issue will close once, but please reopen if there is a problem :)
