### ISSUE TITLE
Alphanumeric Support

### ISSUE THREAD

**Issue by flyinbutrs** [tsuyoshiwada/sequential-number#8]
Similar to #5, but for purely alphanumeric options. So this:

````
a + 1 : 0 : a
````

could output:

````
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
aa
ab
ac
...
````

And base A would be the same but with capital letters.

**Comment by wadackel** [comment]
Hi @flyinbutrs , Thanks for issue !

Reply was delayed .... I will try to fix it soon.

**Comment by flyinbutrs** [comment]
Thanks!

**Comment by MartinMuzatko** [comment]
I'd love to take the chance to point out how brilliant this plugin is.. thank you @tsuyoshiwada

**Comment by wadackel** [comment]
Hi @flyinbutrs .
The `v0.5.0` released :tada:
Please update to new version. Will it work as expected?

**Comment by wadackel** [comment]
You can obtain the following output :smiley:

```
# Input
=> z + 2 : 1 : a

# Output
z
ab
ad
af
ah
```

**Comment by ghost** [comment]
works for me @tsuyoshiwada! thank you!
